### PR TITLE
OMV4 Error. Error setting up entry OMV for openmediavault

### PR DESCRIPTION
**Pull request by MadJoker0815**
OMV4 will throw a python error due to int() in line 198 because of the value 'unknown' van not be converted into an integer.

## Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation

## Checklist

- [x] The code change is tested and works locally.
- [ ] The code has been formatted using Black.
- [ ] Tests have been added to verify that the new code works.
- [ ] Documentation added/updated if required.

### CODE REVIEW

**Comment by tomaae** [comment]
Does it not return hwinfo version?

**Comment by MadJoker0815** [comment]
On my OMV4 the Integration throws an error stating 'unknown' can not be converted.
The Integration then is inactive with an error in the log:
`Logger: homeassistant.config_entries
Source: custom_components/openmediavault/omv_controller.py:198
Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues))
First occurred: 11:05:25 (1 occurrences)
Last logged: 11:05:25
Error setting up entry OMV for openmediavault

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
    await controller.async_hwinfo_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 132, in async_hwinfo_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 198, in get_hwinfo
    if int(self.data["hwinfo"]["version"].split(".")[0]) > 5:
ValueError: invalid literal for int() with base 10: `'unknown'``

**Comment by tomaae** [comment]
so, I checked and it actually had version, but it is capitalized:
https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/engined/rpc/system.inc#L382
According to source code, everything else should be broken too. Does everything work for you?

**Comment by MadJoker0815** [comment]
I only use the OMV filesystem information's. 

But it reports all 30 entity's in 4 devices.

I just realized that the Information is lost after 30min when I activate the automatic polling for updates.
If not the Information stays in place.
So it seems the change breaks the automatic update of the information.
Can we change the information coming from OMV so that it is always lower case? Maybe with a lower() when generating the array?
I'll try to modify the file accordingly and try it out.

**Comment by MadJoker0815** [comment]
It seems like it is not as easy after all. It is not only the capitalization, it is also sometimes different wording. At least according to the site you mentioned.
Maybe we should just switch the default to something like "4.0 or lower" then the script runs as normal.
Just mentions instead of unknown "4.0 or lower"
I also found that there is no information on "Version" in "hwstats" in my case. Also no other information except in file systems "fs".
maybe there is another problem with OMV4 but it was working when i installed it the first time. (2020 or so)

**Comment by tomaae** [comment]
well, OMV4 is EOL for over 2 years. underlaying OS is under LTS only for 3 more months. It would be better idea to upgrade instead of spending lot of time to make it work ;)

**Comment by MadJoker0815** [comment]
I just downgraded to v.1.1.7 here the polling works correctly for the file systems.
In regards to the EOL of OMV4 i will retract this request and just have to upgrade to 6 when it is finally released.
There is a lot of plugins missing in OMV5 and 6 though. (like VirtualBox, Docker, etc.)

**Comment by tomaae** [comment]
I dont ever remember VBox to be available on OMV, maybe some custom plugin. But docker is, using omv-extras

**Pull request closed without merging**
