### PR TITLE
Add Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by LeandroIssa**
Please, Add Brazilian Portuguese Translation

### CODE REVIEW

**Comment by tomaae** [comment]
This in not how translation works, see: https://github.com/tomaae/homeassistant-openmediavault#translation
I have added Brazilian Portuguese to lokalise.
I will be closing this as it would cause conflict with localize in future.

**Comment by LeandroIssa** [comment]
> This in not how translation works, see: https://github.com/tomaae/homeassistant-openmediavault#translation I have added Brazilian Portuguese to lokalise. I will be closing this as it would cause conflict with localise in future.

I couldn't join the openmediavault translation team on lokalise, I tried with my account and with a new account and in both nothing happens using the link.
Could you check the link please?

**Comment by tomaae** [comment]
> > This in not how translation works, see: https://github.com/tomaae/homeassistant-openmediavault#translation I have added Brazilian Portuguese to lokalise. I will be closing this as it would cause conflict with localise in future.
> 
> I couldn't join the openmediavault translation team on lokalise, I tried with my account and with a new account and in both nothing happens using the link. Could you check the link please?

My bad, you can join now.

**Comment by LeandroIssa** [comment]
> > > This in not how translation works, see: https://github.com/tomaae/homeassistant-openmediavault#translation I have added Brazilian Portuguese to lokalise. I will be closing this as it would cause conflict with localise in future.
> > 
> > 
> > I couldn't join the openmediavault translation team on lokalise, I tried with my account and with a new account and in both nothing happens using the link. Could you check the link please?
> 
> My bad, you can join now.

Thanks! The translation has already been done!

**Pull request closed without merging**
